name: kthcloud ci aggregator
on:
  push:
    branches:
      - "main"
    paths:
      - "aggregator/**"
      - ".github/workflows/docker-aggregator.yml"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_AGGREGATOR }}
          password: ${{ secrets.DOCKER_PASSWORD_AGGREGATOR }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./aggregator
          file: ./aggregator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG_AGGREGATOR }}