name: kthcloud ci frontend
on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - ".github/workflows/docker-frontend.yml"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_FRONTEND }}
          password: ${{ secrets.DOCKER_PASSWORD_FRONTEND }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG_FRONTEND }}
  